import Link from 'next/link';
import {getProfiles,getDrivers,getDocuments,getVehicles,getRides,getAccountControls,getVehiclePhotoUrl} from '@/services/data';
import {accountControlAction,reviewDocumentAction} from '@/app/actions';
export const dynamic='force-dynamic';

export default async function DriverDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params;
  const [profiles,drivers,docs,vehicles,rides,controls]=await Promise.all([getProfiles(),getDrivers(),getDocuments(),getVehicles(),getRides(),getAccountControls()]);
  const p=profiles.find((x:any)=>x.id===id),d=drivers.find((x:any)=>x.user_id===id),c=controls.find((x:any)=>x.user_id===id);
  if(!d)return <div>Chauffeur introuvable.</div>;
  const driverVehicles=vehicles.filter((v:any)=>v.driver_id===id);
  const vehicleCards=await Promise.all(driverVehicles.map(async(v:any)=>({...v,photoUrl:await getVehiclePhotoUrl(v.photo_path)})));
  return <div>
    <Link href="/chauffeurs" className="text-blue-700">← Chauffeurs</Link>
    <h1 className="text-3xl font-black mt-3">{p?.first_name} {p?.last_name}</h1>
    <div className="grid lg:grid-cols-2 gap-5 mt-5">
      <section className="card p-5"><h2 className="font-black">Informations</h2><div className="text-sm mt-3 space-y-2"><p>Téléphone : {p?.phone||'—'}</p><p>E-mail : {p?.email||'—'}</p><p>Pays : {p?.country_code||'—'}</p><p>Disponibilité : {d.status}</p><p>Note : {d.rating}</p><p>Courses : {rides.filter((r:any)=>r.driver_id===id).length}</p><p>Véhicules : {driverVehicles.length}</p></div><form action={accountControlAction} className="mt-5 grid gap-2"><input type="hidden" name="userId" value={id}/><input type="hidden" name="role" value="driver"/><select className="input" name="status" defaultValue={c?.admin_status||'pending'}><option value="pending">En attente</option><option value="validated">Validé</option><option value="invalidated">Invalidé</option></select><select className="input" name="active" defaultValue={String(c?.is_active!==false)}><option value="true">Compte actif</option><option value="false">Compte désactivé</option></select><textarea className="input" name="reason" placeholder="Motif interne" defaultValue={c?.internal_reason||''}/><button className="btn">Mettre à jour le compte</button></form></section>
      <section className="card p-5"><h2 className="font-black">Véhicule</h2><p className="text-xs muted mt-1">Immatriculation et photo obligatoires avant mise en ligne.</p><div className="space-y-4 mt-4">{vehicleCards.length?vehicleCards.map((v:any)=><div key={v.id} className="border rounded-2xl overflow-hidden bg-white"><div className="aspect-[16/9] bg-slate-100">{v.photoUrl?<img src={v.photoUrl} alt={`Véhicule ${v.plate_number||''}`} className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-sm text-slate-500">Photo véhicule absente</div>}</div><div className="p-4 text-sm space-y-1"><div className="flex items-center justify-between gap-3"><b>{[v.make,v.model].filter(Boolean).join(' ')||'Véhicule FAST'}</b><span className={`text-xs font-bold ${v.is_active?'text-green-700':'text-slate-500'}`}>{v.is_active?'Actif':'Inactif'}</span></div><p>Immatriculation : <b>{v.plate_number||'—'}</b></p><p>Couleur : {v.color||'—'}</p><p>Catégorie : {v.vehicle_type||'standard'} • {v.seats||4} places</p><p className="text-xs muted">Photo : {v.photo_path?'enregistrée':'manquante'}</p></div></div>):<div className="border border-dashed rounded-xl p-4 text-sm text-amber-700 bg-amber-50">Aucun véhicule enregistré. Ce chauffeur ne peut pas être proposé aux clients.</div>}</div></section>
      <section className="card p-5 lg:col-span-2"><h2 className="font-black">Documents</h2><div className="grid lg:grid-cols-2 gap-3 mt-3">{docs.filter((x:any)=>x.driver_id===id).map((doc:any)=><div key={doc.id} className="border rounded-xl p-3"><div className="flex justify-between gap-3"><div><b>{doc.document_type}</b><div className="text-xs muted">{doc.file_name} • {doc.status}</div>{doc.rejection_reason&&<div className="text-xs text-red-700">{doc.rejection_reason}</div>}</div><a className="btn secondary" href={`/api/documents/${doc.id}`} target="_blank">Ouvrir</a></div><form action={reviewDocumentAction} className="flex gap-2 mt-3"><input type="hidden" name="id" value={doc.id}/><select className="input" name="status" defaultValue={doc.status==='approved'?'approved':'rejected'}><option value="approved">Valider</option><option value="rejected">Refuser</option></select><input className="input flex-1" name="reason" placeholder="Motif de refus"/><button className="btn">Appliquer</button></form></div>)}</div></section>
    </div>
  </div>;
}
