(()=>{'use strict';
const URL='https://ioffjwxfxrqvxttbjeok.supabase.co';
const KEY='sb_publishable_52lG_rrc0j4MG6a0hrCWcQ_oVdqNVvS';
const ACTIONS=URL+'/functions/v1/talentcongo-admin-actions';
const ADMIN_USERS=URL+'/functions/v1/talentcongo-admin-users';
const SQL_URL='https://supabase.com/dashboard/project/ioffjwxfxrqvxttbjeok/sql/new';
const POWERBI_URL='https://app.powerbi.com/';
const sb=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const titles={dashboard:'Tableau de bord',tasks:'Tâches & suivi',candidates:'Candidatures',companies:'Entreprises',accounts:'Espaces clients',departments:'Départements',missions:'Missions',needs:'Besoins',salaries:'Salaires',payments:'Paiements',invoices:'Factures',expenses:'Dépenses',data:'Centre de données',powerbi:'Power BI',sql:'SQL & requêtes',rules:'Paramètres métier',content:'Contenu du site',settings:'Paramètres entreprise',admins:'Administrateurs',audit:'Journal d’audit'};
const state={profile:null,candidates:[],companies:[],accounts:[],missions:[],needs:[],salaries:[],payments:[],invoices:[],expenses:[],tasks:[],departments:[],rules:[],content:[],settings:null,admins:[],audit:[]};
let current='dashboard';
function toast(t){const e=$('toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2600)}
function money(n,c='XAF'){return `${Number(n||0).toLocaleString('fr-FR')} ${esc(c||'XAF')}`}
function date(v){if(!v)return'—';try{return new Date(v).toLocaleDateString('fr-FR')}catch{return String(v)}}
function dt(v){if(!v)return'—';try{return new Date(v).toLocaleString('fr-FR')}catch{return String(v)}}
function accountName(id){return state.accounts.find(x=>x.id===id)?.display_name||'—'}
function missionName(id){return state.missions.find(x=>x.id===id)?.title||'—'}
function status(v){const s=String(v||'');const ok=['Retenu','Validée','active','en_cours','terminee','paye','paid','done','approved','pourvu','sent'].includes(s);const bad=['Archivé','annule','annulee','cancelled','closed','suspended','overdue'].includes(s);const warn=['Nouveau','Nouvelle','À étudier','À contacter','en_traitement','a_payer','partial','partiel','todo','blocked','draft','planifiee','ouvert'].includes(s);return `<span class="status ${ok?'ok':bad?'bad':warn?'warn':''}">${esc(s||'—')}</span>`}
async function setupAvailability(){const {data,error}=await sb.rpc('tc_admin_setup_available');if(!error&&data===true)$('showSetupBtn').classList.remove('hidden');else $('showSetupBtn').classList.add('hidden');return data===true}
async function session(){return (await sb.auth.getSession()).data.session}
async function callFunction(base,path,body={}){const s=await session();if(!s)throw Error('Session expirée.');const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+s.access_token},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||d.detail||'Erreur serveur.');return d}
async function audit(action,target_type='',target_id='',details={}){try{await sb.from('tc_audit_logs').insert({admin_username:state.profile?.display_name||'Administrateur',action,target_type,target_id,details})}catch{}}
async function ensureAdmin(){const s=await session();if(!s)return false;let {data:p}=await sb.from('tc_admin_profiles').select('*').eq('user_id',s.user.id).maybeSingle();if(!p){const available=await setupAvailability();if(available){const name=localStorage.getItem('tc_pending_admin_name')||'Administrateur TalentCongo';const {error}=await sb.rpc('tc_claim_first_admin',{p_display_name:name});if(error){showAuth('Ce compte est connecté mais le rôle administrateur n’a pas pu être initialisé : '+error.message,true);return false}localStorage.removeItem('tc_pending_admin_name');({data:p}=await sb.from('tc_admin_profiles').select('*').eq('user_id',s.user.id).maybeSingle())}}
if(!p||!p.is_active){showAuth('Ce compte n’a pas accès à l’administration TalentCongo.',true);return false}state.profile=p;$('adminIdentity').textContent=`${p.display_name} · ${p.role}`;$('authScreen').classList.add('hidden');$('app').classList.remove('hidden');await loadAll();return true}
function showAuth(msg='',bad=false){$('app').classList.add('hidden');$('authScreen').classList.remove('hidden');if(msg){$('loginNotice').textContent=msg;$('loginNotice').className='notice '+(bad?'bad':'ok')}}
async function login(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;$('loginNotice').textContent='Connexion…';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginNotice').textContent=error.message;$('loginNotice').className='notice bad';return}await ensureAdmin()}
async function magic(){const email=$('loginEmail').value.trim();if(!email){$('loginNotice').textContent='Renseignez votre e-mail.';return}const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});$('loginNotice').className='notice '+(error?'bad':'ok');$('loginNotice').textContent=error?error.message:'Lien de connexion envoyé par e-mail.'}
async function createFirstAdmin(){const name=$('setupName').value.trim()||'Administrateur TalentCongo',email=$('setupEmail').value.trim(),password=$('setupPassword').value;if(password.length<10){$('setupNotice').textContent='Utilisez au moins 10 caractères.';$('setupNotice').className='notice bad';return}localStorage.setItem('tc_pending_admin_name',name);$('setupNotice').textContent='Création du compte…';const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name}}});if(error){$('setupNotice').textContent=error.message;$('setupNotice').className='notice bad';return}if(data.session){await ensureAdmin()}else{$('setupNotice').className='notice ok';$('setupNotice').textContent='Compte créé. Vérifiez votre e-mail si Supabase demande une confirmation, puis reconnectez-vous ici.'}}
async function logout(){await sb.auth.signOut();location.reload()}
function nav(page){current=page;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.querySelectorAll('.nav-button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('pageTitle').textContent=titles[page]||'TalentCongo';filterCurrent()}
async function q(table,order='created_at'){const {data,error}=await sb.from(table).select('*').order(order,{ascending:false});if(error)throw Error(`${table}: ${error.message}`);return data||[]}
async function loadAll(){try{const [c,co,a,m,n,s,p,i,e,t,d,r,ct,st,ad,au]=await Promise.all([q('tc_candidates'),q('tc_company_requests'),q('tc_accounts'),q('tc_missions'),q('tc_needs'),q('tc_salaries'),q('tc_payments'),q('tc_invoices'),q('tc_expenses','expense_date'),q('tc_tasks'),q('tc_departments'),q('tc_business_rules','updated_at'),q('tc_site_content','updated_at'),sb.from('tc_settings').select('*').eq('id',1).maybeSingle(),q('tc_admin_profiles'),q('tc_audit_logs')]);Object.assign(state,{candidates:c,companies:co,accounts:a,missions:m,needs:n,salaries:s,payments:p,invoices:i,expenses:e,tasks:t,departments:d,rules:r,content:ct,settings:st.data||{},admins:ad,audit:au});renderAll();toast('Données FindZone actualisées')}catch(e){toast(e.message);console.error(e)}}
function renderAll(){renderDashboard();renderCandidates();renderCompanies();renderAccounts();renderMissions();renderNeeds();renderSalaries();renderPayments();renderInvoices();renderExpenses();renderTasks();renderDepartments();renderData();renderRules();renderContent();renderSettings();renderAdmins();renderAudit();filterCurrent()}
function renderDashboard(){const ca=state.candidates.filter(x=>!['Retenu','Archivé'].includes(x.status)).length,co=state.companies.filter(x=>!['Validée','Traitée','Archivée'].includes(x.status)).length,open=state.missions.filter(x=>x.status==='en_cours').length,due=state.invoices.filter(x=>['sent','partial','overdue'].includes(x.status)).reduce((s,x)=>s+Number(x.amount_ttc||0),0),todo=state.tasks.filter(x=>!['done','cancelled'].includes(x.status)).length;$('dashboardKpis').innerHTML=[['Candidatures à traiter',ca],['Entreprises à traiter',co],['Missions en cours',open],['Facturation à suivre',money(due)],['Tâches ouvertes',todo]].map(x=>`<div class=kpi><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const recent=[...state.candidates.map(x=>({at:x.created_at,t:`Candidature · ${x.first_name} ${x.last_name}`})),...state.companies.map(x=>({at:x.created_at,t:`Entreprise · ${x.company}`}))].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,7);$('recentActivity').innerHTML=recent.length?recent.map(x=>`<div class=audit-line><small>${dt(x.at)}</small><span>Nouveau dossier</span><b>${esc(x.t)}</b></div>`).join(''):'<div class=empty>Aucune activité récente.</div>';const alerts=[];if(ca)alerts.push(`${ca} candidature(s) à traiter`);if(co)alerts.push(`${co} entreprise(s) à traiter`);const overdue=state.invoices.filter(x=>x.status==='overdue').length;if(overdue)alerts.push(`${overdue} facture(s) en retard`);const urgent=state.tasks.filter(x=>x.priority==='urgent'&&!['done','cancelled'].includes(x.status)).length;if(urgent)alerts.push(`${urgent} tâche(s) urgente(s)`);$('managementAlerts').innerHTML=alerts.length?alerts.map(x=>`<div class=audit-line><small>À traiter</small><span>${status('Attention')}</span><b>${esc(x)}</b></div>`).join(''):'<div class=empty>Aucune alerte importante.</div>'}
function renderCandidates(){$('candidateRows').innerHTML=state.candidates.map(x=>{const ac=state.accounts.find(a=>a.candidate_id===x.id);return `<tr><td><b>${esc(x.first_name)} ${esc(x.last_name)}</b><br><small>${date(x.created_at)}</small></td><td>${esc(x.email)}<br>${esc(x.phone)}</td><td>${esc(x.target_role)}</td><td>${esc(x.availability||'—')}</td><td><select data-candidate-status="${x.id}">${['Nouveau','À étudier','Contacté','Retenu','Archivé'].map(v=>`<option ${v===x.status?'selected':''}>${v}</option>`).join('')}</select></td><td><div class=row-actions><button class=ghost data-doc="candidate:${x.id}:cv">CV</button><button class=ghost data-doc="candidate:${x.id}:identity">Identité</button></div></td><td><div class=row-actions><button class=ghost data-detail="candidates:${x.id}">Détail</button>${ac?'<span class="status ok">Espace actif</span>':`<button class=primary data-invite-candidate="${x.id}">Inviter</button>`}<button class=danger data-delete="tc_candidates:${x.id}">Suppr.</button></div></td></tr>`}).join('')||'<tr><td colspan=7 class=empty>Aucune candidature.</td></tr>'}
function renderCompanies(){$('companyRows').innerHTML=state.companies.map(x=>{const ac=state.accounts.find(a=>a.company_request_id===x.id);return `<tr><td><b>${esc(x.company)}</b><br><small>${date(x.created_at)}</small></td><td>${esc(x.contact_name)}<br>${esc(x.email)}<br>${esc(x.phone)}</td><td>${esc(x.role_title)}</td><td>${Number(x.headcount||1)}</td><td><select data-company-status="${x.id}">${['Nouvelle','À contacter','En cours','Validée','Traitée','Archivée'].map(v=>`<option ${v===x.status?'selected':''}>${v}</option>`).join('')}</select></td><td><div class=row-actions>${x.kbis_path?`<button class=ghost data-doc="company:${x.id}:kbis">Kbis</button>`:''}${x.rib_path?`<button class=ghost data-doc="company:${x.id}:rib">RIB</button>`:''}</div></td><td><div class=row-actions><button class=ghost data-detail="companies:${x.id}">Détail</button>${ac?'<span class="status ok">Espace actif</span>':`<button class=primary data-invite-company="${x.id}">Inviter</button>`}<button class=danger data-delete="tc_company_requests:${x.id}">Suppr.</button></div></td></tr>`}).join('')||'<tr><td colspan=7 class=empty>Aucune entreprise.</td></tr>'}
function renderAccounts(){$('accountRows').innerHTML=state.accounts.map(x=>`<tr><td><b>${esc(x.display_name)}</b></td><td>${status(x.account_type)}</td><td>${esc(x.email)}</td><td>${esc(x.phone||'—')}</td><td>${status(x.status)}</td><td>${date(x.created_at)}</td></tr>`).join('')||'<tr><td colspan=6 class=empty>Aucun espace.</td></tr>'}
function renderMissions(){$('missionRows').innerHTML=state.missions.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(accountName(x.candidate_account_id))}</td><td>${esc(accountName(x.company_account_id))}</td><td>${esc(x.location||'—')}</td><td>${date(x.start_date)} → ${date(x.end_date)}</td><td>${x.rate==null?'—':money(x.rate,x.currency)}</td><td>${status(x.status)}</td><td><div class=row-actions><button class=ghost data-detail="missions:${x.id}">Détail</button><button class=danger data-delete="tc_missions:${x.id}">Suppr.</button></div></td></tr>`).join('')||'<tr><td colspan=8 class=empty>Aucune mission.</td></tr>'}
function renderNeeds(){$('needRows').innerHTML=state.needs.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(accountName(x.company_account_id))}</td><td>${esc(x.location||'—')}</td><td>${x.headcount}</td><td>${status(x.status)}</td><td>${date(x.created_at)}</td><td><button class=danger data-delete="tc_needs:${x.id}">Suppr.</button></td></tr>`).join('')||'<tr><td colspan=7 class=empty>Aucun besoin.</td></tr>'}
function renderSalaries(){$('salaryRows').innerHTML=state.salaries.map(x=>`<tr><td>${esc(accountName(x.candidate_account_id))}</td><td>${esc(missionName(x.mission_id))}</td><td>${date(x.period_start)} → ${date(x.period_end)}</td><td>${money(x.gross_salary,x.currency)}</td><td><b>${money(x.net_salary,x.currency)}</b></td><td>${status(x.payment_status)}</td><td><button class=danger data-delete="tc_salaries:${x.id}">Suppr.</button></td></tr>`).join('')||'<tr><td colspan=7 class=empty>Aucun salaire.</td></tr>'}
function renderPayments(){$('paymentRows').innerHTML=state.payments.map(x=>`<tr><td><b>${esc(x.reference||'Paiement')}</b></td><td>${esc(accountName(x.company_account_id))}</td><td>${esc(missionName(x.mission_id))}</td><td>${money(x.amount,x.currency)}</td><td>${date(x.due_date)}</td><td>${status(x.status)}</td><td><button class=danger data-delete="tc_payments:${x.id}">Suppr.</button></td></tr>`).join('')||'<tr><td colspan=7 class=empty>Aucun paiement.</td></tr>'}
function renderInvoices(){$('invoiceRows').innerHTML=state.invoices.map(x=>`<tr><td><b>${esc(x.invoice_number)}</b></td><td>${esc(accountName(x.company_account_id))}</td><td>${date(x.issue_date)}</td><td>${date(x.due_date)}</td><td>${money(x.amount_ht,x.currency)}</td><td><b>${money(x.amount_ttc,x.currency)}</b></td><td>${status(x.status)}</td><td><button class=danger data-delete="tc_invoices:${x.id}">Suppr.</button></td></tr>`).join('')||'<tr><td colspan=8 class=empty>Aucune facture.</td></tr>'}
function renderExpenses(){$('expenseRows').innerHTML=state.expenses.map(x=>`<tr><td><b>${esc(x.label)}</b></td><td>${esc(x.category||'—')}</td><td>${money(x.amount,x.currency)}</td><td>${date(x.expense_date)}</td><td>${esc(x.payment_method||'—')}</td><td>${status(x.status)}</td><td><button class=danger data-delete="tc_expenses:${x.id}">Suppr.</button></td></tr>`).join('')||'<tr><td colspan=7 class=empty>Aucune dépense.</td></tr>'}
function renderTasks(){$('taskRows').innerHTML=state.tasks.map(x=>`<tr><td><b>${esc(x.title)}</b><br><small>${esc(x.description||'')}</small></td><td>${esc(x.category||'—')}</td><td>${esc(x.assigned_to||'—')}</td><td>${date(x.due_date)}</td><td>${status(x.priority)}</td><td>${status(x.status)}</td><td><button class=danger data-delete="tc_tasks:${x.id}">Suppr.</button></td></tr>`).join('')||'<tr><td colspan=7 class=empty>Aucune tâche.</td></tr>'}
function renderDepartments(){$('departmentRows').innerHTML=state.departments.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.manager_name||'—')}</td><td>${money(x.budget,x.currency)}</td><td>${esc(x.currency)}</td><td>${status(x.status)}</td><td><button class=danger data-delete="tc_departments:${x.id}">Suppr.</button></td></tr>`).join('')||'<tr><td colspan=6 class=empty>Aucun département.</td></tr>'}
function renderData(){const rows=[['Candidatures',state.candidates.length],['Entreprises',state.companies.length],['Espaces',state.accounts.length],['Missions',state.missions.length],['Besoins',state.needs.length],['Salaires',state.salaries.length],['Paiements',state.payments.length],['Factures',state.invoices.length],['Dépenses',state.expenses.length],['Tâches',state.tasks.length]];$('dataSummary').innerHTML=rows.map(x=>`<div class=detail-row><span>${x[0]}</span><b>${x[1]} ligne(s)</b></div>`).join('')}
function renderRules(){$('ruleList').innerHTML=state.rules.map(x=>`<div class=rule-card><h4>${esc(x.label)}</h4><div class=field><label>Catégorie</label><input value="${esc(x.category)}" disabled></div><div class=field style="margin-top:8px"><label>Configuration JSON</label><textarea rows=5 data-rule-value="${x.rule_key}">${esc(JSON.stringify(x.value,null,2))}</textarea></div><div class=toolbar><label><input type=checkbox data-rule-active="${x.rule_key}" ${x.is_active?'checked':''}> Actif</label><button class=primary data-save-rule="${x.rule_key}">Enregistrer</button></div></div>`).join('')||'<div class=empty>Aucune règle.</div>'}
function renderContent(){$('contentEditor').innerHTML=state.content.map(x=>`<div class=panel><div class=panel-head><div><h3>${esc(x.section_key)}</h3><p>Section du site public</p></div><button class=primary data-save-content="${x.section_key}">Enregistrer</button></div><div class=panel-body><div class=field><label>Titre</label><input data-content-title="${x.section_key}" value="${esc(x.title)}"></div><div class=field style="margin-top:10px"><label>Contenu</label><textarea rows=6 data-content-body="${x.section_key}">${esc(x.content)}</textarea></div></div></div>`).join('')||'<div class=empty>Aucune section.</div>'}
function renderSettings(){const s=state.settings||{};['legal_name','registration_number','phone_display','email','whatsapp','city','country','opening_hours','address','website','linkedin','facebook'].forEach(k=>{const e=$('set_'+k);if(e)e.value=s[k]||e.value||''})}
function renderAdmins(){$('adminRows').innerHTML=state.admins.map(x=>`<tr><td><b>${esc(x.display_name)}</b></td><td>${status(x.role)}</td><td>${status(x.is_active?'active':'inactive')}</td><td>${dt(x.last_login_at)}</td><td>${date(x.created_at)}</td></tr>`).join('')||'<tr><td colspan=5 class=empty>Aucun administrateur.</td></tr>'}
function renderAudit(){$('auditRows').innerHTML=state.audit.slice(0,150).map(x=>`<div class=audit-line><small>${dt(x.created_at)}</small><span>${esc(x.admin_username||'Admin')}</span><b>${esc(x.action)} ${x.target_type?`· ${esc(x.target_type)}`:''}</b></div>`).join('')||'<div class=empty>Aucune trace.</div>'}
function detail(type,id){const map={candidates:state.candidates,companies:state.companies,missions:state.missions};const row=map[type]?.find(x=>x.id===id);if(!row)return;$('drawerTitle').textContent=type==='candidates'?`${row.first_name} ${row.last_name}`:type==='companies'?row.company:row.title;$('drawerBody').innerHTML=Object.entries(row).filter(([,v])=>v!=null&&typeof v!=='object').map(([k,v])=>`<div class=detail-row><span>${esc(k.replaceAll('_',' '))}</span><b>${esc(v)}</b></div>`).join('');$('drawer').classList.remove('hidden')}
function openModal(title,html,onSave){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden');const b=$('modalBody').querySelector('[data-modal-save]');if(b)b.onclick=onSave}
function closeModal(){$('modal').classList.add('hidden')}
function options(arr,type){return '<option value="">—</option>'+arr.map(x=>`<option value="${x.id}">${esc(type==='account'?x.display_name:x.title)}</option>`).join('')}
async function createRow(table,row,msg){const {error}=await sb.from(table).insert(row);if(error)throw Error(error.message);await audit(msg,table);closeModal();await loadAll()}
function missionForm(){const cand=state.accounts.filter(x=>x.account_type==='candidate'),comp=state.accounts.filter(x=>x.account_type==='company');openModal('Nouvelle mission',`<div class=form-grid two><div class=field><label>Candidat</label><select id=f_cand>${options(cand,'account')}</select></div><div class=field><label>Entreprise</label><select id=f_comp>${options(comp,'account')}</select></div><div class=field><label>Intitulé</label><input id=f_title></div><div class=field><label>Lieu</label><input id=f_location></div><div class=field><label>Début</label><input id=f_start type=date></div><div class=field><label>Fin</label><input id=f_end type=date></div><div class=field><label>Taux</label><input id=f_rate type=number></div><div class=field><label>Devise</label><select id=f_cur><option>XAF</option><option>EUR</option></select></div><div class=field><label>Statut</label><select id=f_status><option>planifiee</option><option>en_cours</option><option>terminee</option><option>annulee</option></select></div><div class="field full"><label>Description</label><textarea id=f_desc rows=4></textarea></div></div><button data-modal-save class=primary style="margin-top:12px">Créer</button>`,async()=>{try{await createRow('tc_missions',{candidate_account_id:$('f_cand').value||null,company_account_id:$('f_comp').value||null,title:$('f_title').value,location:$('f_location').value,start_date:$('f_start').value||null,end_date:$('f_end').value||null,rate:$('f_rate').value?Number($('f_rate').value):null,currency:$('f_cur').value,status:$('f_status').value,description:$('f_desc').value},'mission_created')}catch(e){toast(e.message)}})}
function needForm(){const comp=state.accounts.filter(x=>x.account_type==='company');openModal('Nouveau besoin',`<div class=form-grid two><div class=field><label>Entreprise</label><select id=f_comp>${options(comp,'account')}</select></div><div class=field><label>Titre</label><input id=f_title></div><div class=field><label>Lieu</label><input id=f_location></div><div class=field><label>Effectif</label><input id=f_head type=number value=1 min=1></div><div class=field><label>Statut</label><select id=f_status><option>ouvert</option><option>en_traitement</option><option>pourvu</option><option>annule</option></select></div><div class="field full"><label>Description</label><textarea id=f_desc></textarea></div></div><button data-modal-save class=primary>Créer</button>`,async()=>{try{await createRow('tc_needs',{company_account_id:$('f_comp').value,title:$('f_title').value,location:$('f_location').value,headcount:Number($('f_head').value)||1,status:$('f_status').value,description:$('f_desc').value},'need_created')}catch(e){toast(e.message)}})}
function salaryForm(){const cand=state.accounts.filter(x=>x.account_type==='candidate');openModal('Nouveau salaire',`<div class=form-grid><div class=field><label>Candidat</label><select id=f_cand>${options(cand,'account')}</select></div><div class=field><label>Mission</label><select id=f_mission>${options(state.missions,'mission')}</select></div><div class=field><label>Statut</label><select id=f_status><option>a_payer</option><option>en_traitement</option><option>paye</option><option>annule</option></select></div><div class=field><label>Début période</label><input id=f_start type=date></div><div class=field><label>Fin période</label><input id=f_end type=date></div><div class=field><label>Heures</label><input id=f_hours type=number value=0></div><div class=field><label>Taux horaire</label><input id=f_rate type=number value=0></div><div class=field><label>Primes</label><input id=f_bonus type=number value=0></div><div class=field><label>Retenues</label><input id=f_ded type=number value=0></div></div><button data-modal-save class=primary>Enregistrer</button>`,async()=>{try{const hours=Number($('f_hours').value)||0,rate=Number($('f_rate').value)||0,bonus=Number($('f_bonus').value)||0,ded=Number($('f_ded').value)||0,gross=hours*rate+bonus;await createRow('tc_salaries',{candidate_account_id:$('f_cand').value,mission_id:$('f_mission').value||null,period_start:$('f_start').value,period_end:$('f_end').value,hours_worked:hours,hourly_rate:rate,bonuses:bonus,deductions:ded,gross_salary:gross,net_salary:gross-ded,currency:'XAF',payment_status:$('f_status').value},'salary_created')}catch(e){toast(e.message)}})}
function paymentForm(){const comp=state.accounts.filter(x=>x.account_type==='company');openModal('Nouveau paiement',`<div class=form-grid two><div class=field><label>Entreprise</label><select id=f_comp>${options(comp,'account')}</select></div><div class=field><label>Mission</label><select id=f_mission>${options(state.missions,'mission')}</select></div><div class=field><label>Référence</label><input id=f_ref></div><div class=field><label>Montant</label><input id=f_amount type=number></div><div class=field><label>Échéance</label><input id=f_due type=date></div><div class=field><label>Statut</label><select id=f_status><option>a_payer</option><option>partiel</option><option>paye</option><option>annule</option></select></div></div><button data-modal-save class=primary>Enregistrer</button>`,async()=>{try{await createRow('tc_payments',{company_account_id:$('f_comp').value,mission_id:$('f_mission').value||null,reference:$('f_ref').value,amount:Number($('f_amount').value)||0,due_date:$('f_due').value||null,status:$('f_status').value,currency:'XAF'},'payment_created')}catch(e){toast(e.message)}})}
function invoiceForm(){const comp=state.accounts.filter(x=>x.account_type==='company');openModal('Nouvelle facture',`<div class=form-grid><div class=field><label>N° facture</label><input id=f_num placeholder="TC-2026-001"></div><div class=field><label>Entreprise</label><select id=f_comp>${options(comp,'account')}</select></div><div class=field><label>Date</label><input id=f_issue type=date></div><div class=field><label>Échéance</label><input id=f_due type=date></div><div class=field><label>Montant HT</label><input id=f_ht type=number></div><div class=field><label>TVA / taxe</label><input id=f_tax type=number value=0></div><div class=field><label>Statut</label><select id=f_status><option>draft</option><option>sent</option><option>partial</option><option>paid</option><option>overdue</option><option>cancelled</option></select></div></div><button data-modal-save class=primary>Créer</button>`,async()=>{try{const ht=Number($('f_ht').value)||0,tax=Number($('f_tax').value)||0;await createRow('tc_invoices',{invoice_number:$('f_num').value,company_account_id:$('f_comp').value||null,issue_date:$('f_issue').value||new Date().toISOString().slice(0,10),due_date:$('f_due').value||null,amount_ht:ht,tax_amount:tax,amount_ttc:ht+tax,currency:'XAF',status:$('f_status').value},'invoice_created')}catch(e){toast(e.message)}})}
function expenseForm(){openModal('Nouvelle dépense',`<div class=form-grid two><div class=field><label>Libellé</label><input id=f_label></div><div class=field><label>Catégorie</label><input id=f_cat></div><div class=field><label>Montant</label><input id=f_amount type=number></div><div class=field><label>Date</label><input id=f_date type=date></div><div class=field><label>Moyen de paiement</label><input id=f_method></div><div class=field><label>Statut</label><select id=f_status><option>draft</option><option>approved</option><option>paid</option><option>cancelled</option></select></div></div><button data-modal-save class=primary>Créer</button>`,async()=>{try{await createRow('tc_expenses',{label:$('f_label').value,category:$('f_cat').value,amount:Number($('f_amount').value)||0,expense_date:$('f_date').value||new Date().toISOString().slice(0,10),payment_method:$('f_method').value,status:$('f_status').value,currency:'XAF'},'expense_created')}catch(e){toast(e.message)}})}
function taskForm(){openModal('Nouvelle tâche',`<div class=form-grid two><div class=field><label>Titre</label><input id=f_title></div><div class=field><label>Catégorie</label><input id=f_cat></div><div class=field><label>Responsable</label><input id=f_assigned></div><div class=field><label>Échéance</label><input id=f_due type=date></div><div class=field><label>Priorité</label><select id=f_priority><option>low</option><option selected>normal</option><option>high</option><option>urgent</option></select></div><div class=field><label>Statut</label><select id=f_status><option>todo</option><option>in_progress</option><option>blocked</option><option>done</option><option>cancelled</option></select></div><div class="field full"><label>Description</label><textarea id=f_desc></textarea></div></div><button data-modal-save class=primary>Créer</button>`,async()=>{try{await createRow('tc_tasks',{title:$('f_title').value,category:$('f_cat').value,assigned_to:$('f_assigned').value,due_date:$('f_due').value||null,priority:$('f_priority').value,status:$('f_status').value,description:$('f_desc').value},'task_created')}catch(e){toast(e.message)}})}
function departmentForm(){openModal('Nouveau département',`<div class=form-grid two><div class=field><label>Nom</label><input id=f_name></div><div class=field><label>Responsable</label><input id=f_manager></div><div class=field><label>Budget</label><input id=f_budget type=number value=0></div><div class=field><label>Devise</label><select id=f_cur><option>XAF</option><option>EUR</option></select></div></div><button data-modal-save class=primary>Créer</button>`,async()=>{try{await createRow('tc_departments',{name:$('f_name').value,manager_name:$('f_manager').value,budget:Number($('f_budget').value)||0,currency:$('f_cur').value,status:'active'},'department_created')}catch(e){toast(e.message)}})}
function adminForm(){if(state.profile?.role!=='super_admin'){toast('Réservé au super administrateur.');return}openModal('Inviter un administrateur',`<div class=form-grid two><div class=field><label>Nom affiché</label><input id=f_name></div><div class=field><label>E-mail</label><input id=f_email type=email></div><div class=field><label>Rôle</label><select id=f_role><option>admin</option><option>rh</option><option>finance</option><option>support</option></select></div></div><button data-modal-save class=primary>Envoyer l’invitation</button>`,async()=>{try{await callFunction(ADMIN_USERS,'/invite',{display_name:$('f_name').value,email:$('f_email').value,role:$('f_role').value});closeModal();toast('Invitation administrateur envoyée.');await loadAll()}catch(e){toast(e.message)}})}
async function deleteRow(table,id){if(!confirm('Confirmer la suppression ?'))return;const {error}=await sb.from(table).delete().eq('id',id);if(error){toast(error.message);return}await audit('delete',table,id);await loadAll()}
async function documentUrl(spec){const [type,id,kind]=spec.split(':');try{const d=await callFunction(ACTIONS,'/document-url',{type,id,kind});window.open(d.url,'_blank','noopener')}catch(e){toast(e.message)}}
async function inviteCandidate(id){try{const d=await callFunction(ACTIONS,'/invite-candidate',{id});toast(`Invitation envoyée à ${d.email}`);await loadAll()}catch(e){toast(e.message)}}
async function inviteCompany(id){try{const d=await callFunction(ACTIONS,'/invite-company',{id});toast(`Invitation envoyée à ${d.email}`);await loadAll()}catch(e){toast(e.message)}}
async function candidateStatus(id,v){const {error}=await sb.from('tc_candidates').update({status:v,updated_at:new Date().toISOString()}).eq('id',id);if(error)toast(error.message);else{await audit('candidate_status','candidate',id,{status:v});await loadAll()}}
async function companyStatus(id,v){const {error}=await sb.from('tc_company_requests').update({status:v,updated_at:new Date().toISOString()}).eq('id',id);if(error)toast(error.message);else{await audit('company_status','company',id,{status:v});await loadAll()}}
function dataset(name){return state[name]||[]}
function csv(name){const rows=dataset(name);if(!rows.length){toast('Aucune donnée à exporter.');return}const keys=[...new Set(rows.flatMap(Object.keys))].filter(k=>!['password_hash','password_salt'].includes(k));const content='\ufeff'+[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(';'))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));a.download=`TalentCongo_${name}_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);audit('export_csv','data',name)}
function sqlFor(table){return `-- TalentCongo / FindZone\nSELECT *\nFROM public.${table}\nORDER BY created_at DESC\nLIMIT 1000;`}
async function saveRule(key){const row=state.rules.find(x=>x.rule_key===key);if(!row)return;try{const raw=document.querySelector(`[data-rule-value="${CSS.escape(key)}"]`).value,value=JSON.parse(raw),active=document.querySelector(`[data-rule-active="${CSS.escape(key)}"]`).checked;const {error}=await sb.from('tc_business_rules').update({value,is_active:active,updated_at:new Date().toISOString()}).eq('rule_key',key);if(error)throw error;await audit('business_rule_updated','rule',key);await loadAll()}catch(e){toast('Configuration invalide : '+e.message)}}
async function saveContent(key){const title=document.querySelector(`[data-content-title="${CSS.escape(key)}"]`).value,content=document.querySelector(`[data-content-body="${CSS.escape(key)}"]`).value;const {error}=await sb.from('tc_site_content').update({title,content,updated_at:new Date().toISOString()}).eq('section_key',key);if(error)toast(error.message);else{await audit('site_content_updated','content',key);toast('Contenu enregistré.');await loadAll()}}
async function saveSettings(){const keys=['legal_name','registration_number','phone_display','email','whatsapp','city','country','opening_hours','address','website','linkedin','facebook'],row={id:1,updated_at:new Date().toISOString()};keys.forEach(k=>row[k]=$('set_'+k).value);const {error}=await sb.from('tc_settings').upsert(row,{onConflict:'id'});if(error)toast(error.message);else{await audit('settings_updated','settings','1');toast('Paramètres enregistrés.');await loadAll()}}
function filterCurrent(){const q=($('globalSearch').value||'').trim().toLowerCase(),page=$(`page-${current}`);if(!page)return;page.querySelectorAll('tbody tr').forEach(tr=>tr.style.display=!q||(tr.innerText||'').toLowerCase().includes(q)?'':'none')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page)nav(b.dataset.page);if(b.dataset.go)nav(b.dataset.go);if(b.dataset.detail){const [t,id]=b.dataset.detail.split(':');detail(t,id)}if(b.dataset.delete){const [t,id]=b.dataset.delete.split(':');deleteRow(t,id)}if(b.dataset.doc)documentUrl(b.dataset.doc);if(b.dataset.inviteCandidate)inviteCandidate(b.dataset.inviteCandidate);if(b.dataset.inviteCompany)inviteCompany(b.dataset.inviteCompany);if(b.dataset.export)csv(b.dataset.export);if(b.dataset.saveRule)saveRule(b.dataset.saveRule);if(b.dataset.saveContent)saveContent(b.dataset.saveContent)});
document.addEventListener('change',e=>{if(e.target.dataset.candidateStatus)candidateStatus(e.target.dataset.candidateStatus,e.target.value);if(e.target.dataset.companyStatus)companyStatus(e.target.dataset.companyStatus,e.target.value)});
$('loginBtn').onclick=login;$('magicBtn').onclick=magic;$('showSetupBtn').onclick=()=>{$('loginBox').classList.add('hidden');$('setupBox').classList.remove('hidden')};$('backLoginBtn').onclick=()=>{$('setupBox').classList.add('hidden');$('loginBox').classList.remove('hidden')};$('setupBtn').onclick=createFirstAdmin;$('logoutBtn').onclick=logout;$('refreshBtn').onclick=loadAll;$('globalSearch').oninput=filterCurrent;$('drawerClose').onclick=()=>$('drawer').classList.add('hidden');$('modalClose').onclick=closeModal;$('openMissionForm').onclick=missionForm;$('openNeedForm').onclick=needForm;$('openSalaryForm').onclick=salaryForm;$('openPaymentForm').onclick=paymentForm;$('openInvoiceForm').onclick=invoiceForm;$('openExpenseForm').onclick=expenseForm;$('openTaskForm').onclick=taskForm;$('openDepartmentForm').onclick=departmentForm;$('openAdminForm').onclick=adminForm;$('saveSettingsBtn').onclick=saveSettings;$('extractCsv').onclick=()=>csv($('extractDataset').value);$('extractPowerBi').onclick=()=>{csv($('extractDataset').value);window.open(POWERBI_URL,'_blank','noopener')};$('extractSql').onclick=()=>{const map={candidates:'tc_candidates',companies:'tc_company_requests',accounts:'tc_accounts',missions:'tc_missions',needs:'tc_needs',salaries:'tc_salaries',payments:'tc_payments',invoices:'tc_invoices',expenses:'tc_expenses',tasks:'tc_tasks'},t=map[$('extractDataset').value]||'tc_candidates';$('sqlDataset').value=t;$('sqlCode').textContent=sqlFor(t);nav('sql')};$('openPowerBi').onclick=()=>window.open(POWERBI_URL,'_blank','noopener');$('openSqlEditor').onclick=()=>window.open(SQL_URL,'_blank','noopener');$('generateSql').onclick=()=>{$('sqlCode').textContent=sqlFor($('sqlDataset').value);navigator.clipboard?.writeText($('sqlCode').textContent);toast('Requête SQL générée et copiée.')};
sb.auth.onAuthStateChange((event,s)=>{if(event==='SIGNED_IN'&&s)setTimeout(ensureAdmin,80);if(event==='SIGNED_OUT')showAuth()});
(async()=>{await setupAvailability();const s=await session();if(s)await ensureAdmin();else showAuth()})();
})();