(()=>{
'use strict';
const API='https://hmwxwzfcpdvgzjgxruup.supabase.co/functions/v1/fast-admin-api';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(v).toLocaleString('fr-FR'):'—';
const money=(v,c='EUR')=>{try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:['XAF','XOF','JPY'].includes(c)?0:2}).format(Number(v||0))}catch{return `${Number(v||0).toLocaleString('fr-FR')} ${c}`}};
let adminToken=localStorage.getItem('fast_admin_token')||'',currentPage='dashboard',loading=false;
const state={profiles:[],drivers:[],locations:[],vehicles:[],documents:[],payouts:[],rides:[],payments:[],markets:[],pricing:[]};

function toast(m){const t=$('toast');if(!t)return;t.textContent=String(m||'');t.classList.add('on');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('on'),2800)}
function modal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function setLoginVisible(v){$('loginView').classList.toggle('hidden',!v);$('adminView').classList.toggle('hidden',v);document.body.classList.toggle('admin-open',!v)}
function logout(silent=false){adminToken='';localStorage.removeItem('fast_admin_token');setLoginVisible(true);if(!silent)toast('Déconnecté')}
async function request(path,opts={}){
  const headers={'Content-Type':'application/json',...(opts.headers||{})};if(adminToken)headers['x-fast-admin-token']=adminToken;
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
  try{
    const r=await fetch(API+path,{...opts,headers,signal:opts.signal||controller.signal,cache:'no-store'});let d={};try{d=await r.json()}catch{}
    if(r.status===401&&path!='/login'){logout(true);throw new Error('Session expirée. Reconnectez-vous.')}
    if(!r.ok||d.ok===false)throw new Error(d.error||d.detail||`HTTP ${r.status}`);return d;
  }catch(e){if(e?.name==='AbortError')throw new Error('Délai réseau dépassé.');throw e}finally{clearTimeout(timer)}
}

async function login(){
  const user=($('loginEmail').value||'').trim(),password=$('loginPassword').value||'',btn=$('loginBtn');
  $('loginError').textContent='';if(!user||!password){$('loginError').textContent='Entrez votre identifiant et votre mot de passe.';return}
  btn.disabled=true;btn.textContent='Connexion…';
  try{const d=await request('/login',{method:'POST',body:JSON.stringify({username:user,password})});adminToken=d.token;localStorage.setItem('fast_admin_token',adminToken);$('loginPassword').value='';setLoginVisible(false);await refreshAll();toast('Bienvenue dans FAST Administration')}
  catch(e){$('loginError').textContent=e.message||'Connexion impossible'}finally{btn.disabled=false;btn.textContent='Se connecter'}
}

async function refreshAll(){
  if(loading)return;loading=true;const b=$('refreshBtn');if(b){b.disabled=true;b.textContent='Actualisation…'}
  try{
    const d=await request('/snapshot');const x=d.data||{};
    Object.assign(state,{profiles:x.profiles||[],drivers:x.drivers||[],locations:x.driver_locations||[],vehicles:x.vehicles||[],documents:x.driver_documents||[],payouts:x.driver_payout_profiles||[],rides:x.rides||[],payments:x.payments||[],markets:x.market_configs||[],pricing:x.market_pricing||[]});
    renderAll();
  }catch(e){toast(e.message)}finally{loading=false;if(b){b.disabled=false;b.textContent='Actualiser'}}
}

function profile(id){return state.profiles.find(x=>x.id===id)||null}
function fullName(id){const p=profile(id);return p?`${p.first_name||''} ${p.last_name||''}`.trim()||String(id||'').slice(0,8):id?String(id).slice(0,8):'—'}
function countryName(code){return state.markets.find(x=>x.country_code===code)?.country_name||code||'—'}
function pill(text,kind=''){return `<span class="pill ${kind}">${esc(text)}</span>`}
function statusKind(s){return ['paid','approved','completed','available','verified'].includes(String(s))?'ok':['failed','rejected','cancelled','offline'].includes(String(s))?'bad':['pending','searching','authorized','driver_arriving','in_progress','accepted'].includes(String(s))?'warn':'blue'}
function pageTitle(p){return({dashboard:'Tableau de bord',drivers:'Chauffeurs',clients:'Clients',documents:'Documents chauffeurs',payments:'Paiements clients',payouts:'Paie chauffeurs',rides:'Courses',markets:'Pays, paiements & tarifs'})[p]||'FAST N°1'}
function renderAll(){renderDashboard();renderDrivers();renderClients();renderDocuments();renderPayments();renderPayouts();renderRides();renderMarkets();fillCountryFilter();$('pendingDocBadge').textContent=state.documents.filter(d=>d.status==='pending').length}

function renderDashboard(){
  const clients=state.profiles.filter(p=>String(p.role)==='client').length,drivers=state.drivers.length,verified=state.drivers.filter(d=>d.is_verified).length;
  const active=state.rides.filter(r=>['searching','accepted','driver_arriving','in_progress'].includes(r.status)).length,completed=state.rides.filter(r=>r.status==='completed').length,pendingDocs=state.documents.filter(d=>d.status==='pending').length;
  $('stats').innerHTML=[['Clients',clients,'Comptes passagers'],['Chauffeurs',drivers,`${verified} vérifiés`],['Courses actives',active,`${completed} terminées`],['Documents à contrôler',pendingDocs,'Validation interne']].map(([a,b,c])=>`<div class="stat"><small>${a}</small><b>${b}</b><span>${c}</span></div>`).join('');
  const rr=[...state.rides].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,7);$('recentRides').innerHTML=rr.length?'<div class="mini-list">'+rr.map(r=>`<div class="mini-item"><div><b>${esc(r.pickup_address||'Départ')} → ${esc(r.destination_address||'Destination')}</b><small>${esc(fullName(r.client_id))} • ${fmtDate(r.created_at)}</small></div>${pill(r.status,statusKind(r.status))}</div>`).join('')+'</div>':'<span class="muted">Aucune course.</span>';
  const dd=[...state.documents].filter(d=>d.status==='pending').sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,7);$('recentDocs').innerHTML=dd.length?'<div class="mini-list">'+dd.map(d=>`<div class="mini-item"><div><b>${esc(fullName(d.driver_id))}</b><small>${esc(d.document_type)} • ${fmtDate(d.created_at)}</small></div>${pill('À vérifier','warn')}</div>`).join('')+'</div>':'<span class="muted">Aucun document en attente.</span>';
  const rev={};state.payments.filter(p=>p.status==='paid').forEach(p=>rev[p.currency]=(rev[p.currency]||0)+Number(p.amount||0));$('revenueByCurrency').innerHTML=Object.keys(rev).length?Object.entries(rev).map(([c,v])=>`<div class="revenue-card"><small>${esc(c)}</small><b>${money(v,c)}</b></div>`).join(''):'<span class="muted">Aucune recette encaissée.</span>';
}
function fillCountryFilter(){const s=$('driverCountryFilter');if(!s)return;const cur=s.value,codes=[...new Set([...state.locations.map(x=>x.country_code),...state.profiles.map(x=>x.country_code)].filter(Boolean))].sort();s.innerHTML='<option value="">Tous les pays</option>'+codes.map(c=>`<option value="${esc(c)}">${esc(countryName(c))} (${esc(c)})</option>`).join('');s.value=cur}
function renderDrivers(){const term=($('driverSearch')?.value||'').toLowerCase(),cc=$('driverCountryFilter')?.value||'';const rows=state.drivers.filter(d=>{const p=profile(d.user_id),loc=state.locations.find(x=>x.driver_id===d.user_id),hay=`${p?.first_name||''} ${p?.last_name||''} ${p?.phone||''}`.toLowerCase();return(!term||hay.includes(term))&&(!cc||(loc?.country_code||p?.country_code)===cc)});$('driversBody').innerHTML=rows.map(d=>{const p=profile(d.user_id),loc=state.locations.find(x=>x.driver_id===d.user_id),pay=state.payouts.find(x=>x.driver_id===d.user_id);return `<tr><td><span class="name">${esc(fullName(d.user_id))}</span><span class="sub">${esc(p?.phone||d.user_id)}</span></td><td>${esc(loc?.country_name||countryName(loc?.country_code||p?.country_code))}</td><td>${pill(d.status,statusKind(d.status))}</td><td>${d.is_verified?pill('Validé','ok'):pill('À valider','warn')}</td><td>⭐ ${Number(d.rating||0).toFixed(1)}</td><td>${Number(d.total_rides||0)}</td><td>${pay?.is_complete?pill(pay.payout_status||'configuré',pay.payout_status==='verified'?'ok':'warn'):pill('À compléter','bad')}</td><td><div class="row-actions"><button data-driver-verify="${d.user_id}" data-value="${!d.is_verified}">${d.is_verified?'Retirer validation':'Valider chauffeur'}</button></div></td></tr>`}).join('')||'<tr><td colspan="8" class="muted">Aucun chauffeur.</td></tr>';document.querySelectorAll('[data-driver-verify]').forEach(b=>b.onclick=()=>setDriverVerified(b.dataset.driverVerify,b.dataset.value==='true'))}
async function setDriverVerified(id,value){try{await request('/driver/verify',{method:'POST',body:JSON.stringify({id,value})});toast(value?'Chauffeur validé':'Validation retirée');await refreshAll()}catch(e){toast(e.message)}}
function renderClients(){const term=($('clientSearch')?.value||'').toLowerCase();const rows=state.profiles.filter(p=>String(p.role)==='client').filter(p=>!term||`${p.first_name||''} ${p.last_name||''} ${p.phone||''}`.toLowerCase().includes(term));$('clientsBody').innerHTML=rows.map(p=>{const rides=state.rides.filter(r=>r.client_id===p.id),paid=state.payments.filter(x=>x.user_id===p.id&&x.status==='paid'),by={};paid.forEach(x=>by[x.currency]=(by[x.currency]||0)+Number(x.amount||0));const spend=Object.entries(by).map(([c,v])=>money(v,c)).join(' • ')||'—';return `<tr><td><span class="name">${esc(fullName(p.id))}</span><span class="sub">${esc(String(p.id).slice(0,8))}</span></td><td>${esc(p.phone||'—')}</td><td>${esc(countryName(p.country_code))}</td><td>${fmtDate(p.created_at)}</td><td>${rides.length}</td><td>${esc(spend)}</td></tr>`}).join('')||'<tr><td colspan="6" class="muted">Aucun client.</td></tr>'}
function renderDocuments(){const f=$('docStatusFilter')?.value??'pending';let rows=[...state.documents].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(f)rows=rows.filter(d=>d.status===f);$('documentsBody').innerHTML=rows.map(d=>`<tr><td><span class="name">${esc(fullName(d.driver_id))}</span></td><td>${esc(d.document_type)}</td><td>${esc(d.file_name||'—')}${d.file_size_bytes?`<span class="sub">${Math.round(Number(d.file_size_bytes)/1024)} Ko</span>`:''}</td><td>${esc(countryName(d.country_code))}</td><td>${pill(d.status,statusKind(d.status))}${d.rejection_reason?`<span class="sub">${esc(d.rejection_reason)}</span>`:''}</td><td>${fmtDate(d.created_at)}</td><td><div class="row-actions"><button data-doc-open="${d.id}">Ouvrir</button>${d.status!=='approved'?`<button class="approve" data-doc-approve="${d.id}">Valider</button>`:''}${d.status!=='rejected'?`<button class="reject" data-doc-reject="${d.id}">Refuser</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Aucun document.</td></tr>';document.querySelectorAll('[data-doc-open]').forEach(b=>b.onclick=()=>openDocument(b.dataset.docOpen));document.querySelectorAll('[data-doc-approve]').forEach(b=>b.onclick=()=>reviewDocument(b.dataset.docApprove,'approved'));document.querySelectorAll('[data-doc-reject]').forEach(b=>b.onclick=()=>reviewDocument(b.dataset.docReject,'rejected'))}
async function openDocument(id){try{const d=await request('/document/url',{method:'POST',body:JSON.stringify({id})});const img=/\.(jpg|jpeg|png|webp|heic|heif)$/i.test(d.file_name||'');modal('Document chauffeur',img?`<img src="${esc(d.url)}" style="max-width:100%;border-radius:12px" alt="Document chauffeur"><p><a href="${esc(d.url)}" target="_blank" rel="noopener">Ouvrir en plein écran</a></p>`:`<iframe class="doc-preview" src="${esc(d.url)}"></iframe><p><a href="${esc(d.url)}" target="_blank" rel="noopener">Ouvrir le document</a></p>`)}catch(e){toast(e.message)}}
async function reviewDocument(id,status){let reason='';if(status==='rejected'){reason=prompt('Motif du refus :')||'';if(!reason.trim())return}try{await request('/document/review',{method:'POST',body:JSON.stringify({id,status,reason})});toast(status==='approved'?'Document validé':'Document refusé');await refreshAll()}catch(e){toast(e.message)}}
function renderPayments(){let rows=[...state.payments].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const f=$('paymentStatusFilter')?.value||'';if(f)rows=rows.filter(x=>x.status===f);$('paymentsBody').innerHTML=rows.map(p=>`<tr><td>${fmtDate(p.created_at)}</td><td>${esc(fullName(p.user_id))}</td><td>${esc(p.ride_id?.slice(0,8)||'—')}</td><td>${esc(p.provider||p.method_type||'—')}</td><td class="name">${money(p.amount,p.currency)}</td><td>${esc(p.currency||'—')}</td><td>${pill(p.status,statusKind(p.status))}</td><td>${esc(p.provider_reference||'—')}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">Aucun paiement.</td></tr>'}
function renderPayouts(){$('payoutsBody').innerHTML=state.payouts.map(p=>{const coords=p.payout_method==='mobile_money'?`${p.mobile_operator||''} ${p.phone_number||''}`:`${p.bank_name||''} ${p.iban_or_account||''} ${p.bank_bic_swift||''}`.trim();return `<tr><td>${esc(fullName(p.driver_id))}</td><td>${esc(countryName(p.country_code))}</td><td>${esc(p.payout_method||'—')}</td><td>${esc(p.account_holder||'—')}</td><td>${esc(coords||'—')}</td><td>${esc(p.payout_currency||'—')}</td><td>${pill(p.payout_status||'pending',statusKind(p.payout_status))}</td><td><div class="row-actions">${p.payout_status!=='verified'?`<button data-pay-verify="${p.driver_id}">Valider</button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="8" class="muted">Aucun profil de paie.</td></tr>';document.querySelectorAll('[data-pay-verify]').forEach(b=>b.onclick=()=>verifyPayout(b.dataset.payVerify))}
async function verifyPayout(driver_id){try{await request('/payout/verify',{method:'POST',body:JSON.stringify({driver_id})});toast('Coordonnées de paie validées');await refreshAll()}catch(e){toast(e.message)}}
function renderRides(){let rows=[...state.rides].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const f=$('rideStatusFilter')?.value||'';if(f)rows=rows.filter(r=>r.status===f);$('ridesBody').innerHTML=rows.map(r=>`<tr><td>${fmtDate(r.created_at)}</td><td>${esc(r.pickup_country_name||countryName(r.pickup_country_code))}</td><td>${esc(fullName(r.client_id))}</td><td>${esc(fullName(r.driver_id))}</td><td>${esc(r.pickup_address||'—')}</td><td>${esc(r.destination_address||'—')}</td><td>${money(r.final_price??r.estimated_price,r.currency||'EUR')}</td><td>${esc(r.payment_method||'—')}</td><td>${pill(r.status,statusKind(r.status))}</td></tr>`).join('')||'<tr><td colspan="9" class="muted">Aucune course.</td></tr>'}
function renderMarkets(){$('marketsGrid').innerHTML=state.markets.map(m=>`<div class="market-card"><div style="display:flex;justify-content:space-between;gap:10px"><div><h3>${esc(m.country_name)} <small>${esc(m.country_code)}</small></h3><p>${esc(m.currency)} • ${esc(m.locale)}</p></div>${pill(m.enabled?'Actif':'Inactif',m.enabled?'ok':'bad')}</div><div class="methods">${(m.payment_methods||[]).map(x=>pill(x,'blue')).join('')}</div><p>Paie : ${(m.payout_methods||[]).map(esc).join(', ')||'—'}</p><p>Documents : ${(m.document_requirements||[]).length} requis</p><button data-market-edit="${esc(m.country_code)}">Modifier</button></div>`).join('')||'<span class="muted">Aucun pays configuré.</span>';document.querySelectorAll('[data-market-edit]').forEach(b=>b.onclick=()=>editMarket(b.dataset.marketEdit));$('pricingBody').innerHTML=state.pricing.map(p=>`<tr><td>${esc(countryName(p.country_code))}</td><td>${esc(p.service_type)}</td><td>${esc(p.base_fare)}</td><td>${esc(p.per_km)}</td><td>${esc(p.per_minute)}</td><td>${esc(p.minimum_fare)}</td><td>${esc(p.booking_fee)}</td><td>${esc(p.currency)}</td><td><div class="row-actions"><button data-price-edit="${p.id}">Modifier</button></div></td></tr>`).join('')||'<tr><td colspan="9" class="muted">Aucun tarif.</td></tr>';document.querySelectorAll('[data-price-edit]').forEach(b=>b.onclick=()=>editPricing(b.dataset.priceEdit))}
function marketForm(m={}){return `<div class="form-grid"><label>Code pays ISO<input id="mCode" maxlength="2" value="${esc(m.country_code||'')}"></label><label>Nom du pays<input id="mName" value="${esc(m.country_name||'')}"></label><label>Devise<input id="mCurrency" maxlength="3" value="${esc(m.currency||'EUR')}"></label><label>Locale<input id="mLocale" value="${esc(m.locale||'fr-FR')}"></label><label class="full">Paiements (virgules)<input id="mPayments" value="${esc((m.payment_methods||['card','cash','wallet']).join(','))}"></label><label class="full">Paie chauffeur<input id="mPayouts" value="${esc((m.payout_methods||['bank']).join(','))}"></label><label class="full">Opérateurs Mobile Money<input id="mOperators" value="${esc((m.mobile_money_operators||[]).join(','))}"></label><label class="full">Documents requis<input id="mDocs" value="${esc((m.document_requirements||['identity','license','vehicle_registration','insurance','driver_photo','address_proof']).join(','))}"></label><label>Actif<select id="mEnabled"><option value="true" ${m.enabled!==false?'selected':''}>Oui</option><option value="false" ${m.enabled===false?'selected':''}>Non</option></select></label></div><div class="actions"><button id="cancelMarketBtn">Annuler</button><button id="saveMarketBtn" class="primary">Enregistrer</button></div>`}
function editMarket(code){const m=state.markets.find(x=>x.country_code===code);modal(m?'Modifier le pays':'Ajouter un pays',marketForm(m||{}));if(m)$('mCode').disabled=true;$('cancelMarketBtn').onclick=closeModal;$('saveMarketBtn').onclick=saveMarket}
async function saveMarket(){const val=id=>$(id).value.trim(),arr=id=>val(id).split(',').map(x=>x.trim()).filter(Boolean);const row={country_code:val('mCode').toUpperCase(),country_name:val('mName'),currency:val('mCurrency').toUpperCase(),locale:val('mLocale'),enabled:$('mEnabled').value==='true',payment_methods:arr('mPayments'),payout_methods:arr('mPayouts'),mobile_money_operators:arr('mOperators'),document_requirements:arr('mDocs')};try{await request('/market/save',{method:'POST',body:JSON.stringify(row)});closeModal();toast('Pays enregistré');await refreshAll()}catch(e){toast(e.message)}}
function editPricing(id){const p=state.pricing.find(x=>x.id===id);if(!p)return;modal(`Tarif • ${countryName(p.country_code)} • ${p.service_type}`,`<div class="form-grid"><label>Base<input id="prBase" type="number" step="0.01" min="0" value="${esc(p.base_fare)}"></label><label>Par km<input id="prKm" type="number" step="0.01" min="0" value="${esc(p.per_km)}"></label><label>Par minute<input id="prMin" type="number" step="0.01" min="0" value="${esc(p.per_minute)}"></label><label>Minimum<input id="prMinimum" type="number" step="0.01" min="0" value="${esc(p.minimum_fare)}"></label><label>Frais réservation<input id="prBooking" type="number" step="0.01" min="0" value="${esc(p.booking_fee)}"></label><label>Devise<input id="prCurrency" maxlength="3" value="${esc(p.currency)}"></label></div><div class="actions"><button id="cancelPriceBtn">Annuler</button><button id="savePricingBtn" class="primary">Enregistrer</button></div>`);$('cancelPriceBtn').onclick=closeModal;$('savePricingBtn').onclick=()=>savePricing(id)}
async function savePricing(id){const row={id,base_fare:Number($('prBase').value),per_km:Number($('prKm').value),per_minute:Number($('prMin').value),minimum_fare:Number($('prMinimum').value),booking_fee:Number($('prBooking').value),currency:$('prCurrency').value.trim().toUpperCase()};try{await request('/pricing/update',{method:'POST',body:JSON.stringify(row)});closeModal();toast('Tarif mis à jour');await refreshAll()}catch(e){toast(e.message)}}
function exportRows(){switch(currentPage){case'drivers':return state.drivers.map(d=>{const p=profile(d.user_id),l=state.locations.find(x=>x.driver_id===d.user_id),pay=state.payouts.find(x=>x.driver_id===d.user_id);return{Nom:fullName(d.user_id),Telephone:p?.phone||'',Pays:l?.country_name||countryName(p?.country_code),Statut:d.status,Verifie:d.is_verified?'Oui':'Non',Note:d.rating,Courses:d.total_rides,Paie:pay?.payout_status||'non configurée'}});case'clients':return state.profiles.filter(p=>String(p.role)==='client').map(p=>({Nom:fullName(p.id),Telephone:p.phone||'',Pays:countryName(p.country_code),Inscription:p.created_at,Courses:state.rides.filter(r=>r.client_id===p.id).length}));case'documents':return state.documents.map(d=>({Chauffeur:fullName(d.driver_id),Type:d.document_type,Fichier:d.file_name,Pays:countryName(d.country_code),Statut:d.status,Motif:d.rejection_reason||'',Date:d.created_at}));case'payments':return state.payments.map(p=>({Date:p.created_at,Client:fullName(p.user_id),Course:p.ride_id,Methode:p.provider||p.method_type,Montant:p.amount,Devise:p.currency,Statut:p.status,Reference:p.provider_reference||''}));case'payouts':return state.payouts.map(p=>({Chauffeur:fullName(p.driver_id),Pays:countryName(p.country_code),Mode:p.payout_method,Titulaire:p.account_holder,Operateur:p.mobile_operator,Telephone:p.phone_number,Banque:p.bank_name,Compte:p.iban_or_account,SWIFT:p.bank_bic_swift,Devise:p.payout_currency,Statut:p.payout_status}));case'rides':return state.rides.map(r=>({Date:r.created_at,Pays:r.pickup_country_name||countryName(r.pickup_country_code),Client:fullName(r.client_id),Chauffeur:fullName(r.driver_id),Depart:r.pickup_address,Destination:r.destination_address,Prix:r.final_price??r.estimated_price,Devise:r.currency,Paiement:r.payment_method,Statut:r.status}));case'markets':return state.pricing.map(p=>({Pays:countryName(p.country_code),Code:p.country_code,Service:p.service_type,Base:p.base_fare,ParKm:p.per_km,ParMinute:p.per_minute,Minimum:p.minimum_fare,Reservation:p.booking_fee,Devise:p.currency}));default:return[{Indicateur:'Clients',Valeur:state.profiles.filter(p=>String(p.role)==='client').length},{Indicateur:'Chauffeurs',Valeur:state.drivers.length},{Indicateur:'Courses',Valeur:state.rides.length},{Indicateur:'Paiements',Valeur:state.payments.length},{Indicateur:'Documents en attente',Valeur:state.documents.filter(d=>d.status==='pending').length}]}}
function exportExcel(){if(!window.XLSX)return toast('Module Excel indisponible');try{const ws=XLSX.utils.json_to_sheet(exportRows()),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,pageTitle(currentPage).slice(0,31));XLSX.writeFile(wb,`FAST_${currentPage}_${new Date().toISOString().slice(0,10)}.xlsx`)}catch(e){toast('Export impossible : '+e.message)}}
function switchPage(page){currentPage=page;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('pageTitle').textContent=pageTitle(page);if(innerWidth<761)window.scrollTo({top:0,behavior:'smooth'})}
function wire(){
  $('loginBtn').onclick=login;$('loginEmail').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginPassword').focus()});$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').onclick=()=>logout();$('refreshBtn').onclick=refreshAll;$('exportBtn').onclick=exportExcel;$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};
  document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$('driverSearch').oninput=renderDrivers;$('driverCountryFilter').onchange=renderDrivers;$('clientSearch').oninput=renderClients;$('docStatusFilter').onchange=renderDocuments;$('paymentStatusFilter').onchange=renderPayments;$('rideStatusFilter').onchange=renderRides;$('newMarketBtn').onclick=()=>editMarket('');
}
async function boot(){wire();setLoginVisible(true);if(!adminToken)return;try{setLoginVisible(false);await refreshAll()}catch{logout(true)}}
window.closeModal=closeModal;window.addEventListener('load',boot,{once:true});
})();
