(()=>{
'use strict';
const API='https://hmwxwzfcpdvgzjgxruup.supabase.co/functions/v1/fast-admin-api';
const $=id=>document.getElementById(id);
const money=(v,c='EUR')=>{try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:['XAF','XOF','JPY'].includes(c)?0:2}).format(Number(v||0))}catch{return `${Number(v||0).toLocaleString('fr-FR')} ${c}`}};
function token(){return localStorage.getItem('fast_admin_token')||''}
function toastMsg(m){if(typeof toast==='function')return toast(m);const t=$('toast');if(t){t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2600)}}
async function snapshot(){const r=await fetch(API+'/snapshot',{headers:{'Content-Type':'application/json','x-fast-admin-token':token()},cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok||d.ok===false)throw new Error(d.error||`HTTP ${r.status}`);return d.data||{}}
function indexBy(rows,key='id'){return Object.fromEntries((rows||[]).map(x=>[x[key],x]))}
function cleanDate(v){if(!v)return'';try{return new Date(v).toLocaleString('fr-FR')}catch{return String(v)}}
function autosize(ws,rows){const headers=Object.keys(rows[0]||{});ws['!cols']=headers.map(h=>({wch:Math.min(42,Math.max(12,h.length+2,...rows.slice(0,250).map(r=>String(r[h]??'').length+2)))}));if(headers.length&&rows.length)ws['!autofilter']={ref:`A1:${XLSX.utils.encode_col(headers.length-1)}${rows.length+1}`};ws['!freeze']={xSplit:0,ySplit:1,topLeftCell:'A2',activePane:'bottomLeft',state:'frozen'}}
function addSheet(wb,name,rows){const data=rows.length?rows:[{Information:'Aucune donnée disponible'}];const ws=XLSX.utils.json_to_sheet(data);autosize(ws,data);XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31));return ws}
function buildData(x){
  const profiles=x.profiles||[],drivers=x.drivers||[],locations=x.driver_locations||[],vehicles=x.vehicles||[],docs=x.driver_documents||[],payouts=x.driver_payout_profiles||[],rides=x.rides||[],payments=x.payments||[],markets=x.market_configs||[],pricing=x.market_pricing||[];
  const p=indexBy(profiles),loc=Object.fromEntries(locations.map(v=>[v.driver_id,v])),veh=indexBy(vehicles),market=Object.fromEntries(markets.map(v=>[v.country_code,v]));
  const name=id=>{const q=p[id]||{};return `${q.first_name||''} ${q.last_name||''}`.trim()||String(id||'').slice(0,8)||'—'};
  const clients=profiles.filter(v=>String(v.role)==='client').map(v=>{const cr=rides.filter(r=>r.client_id===v.id),cp=payments.filter(z=>z.user_id===v.id&&z.status==='paid');const totals={};cp.forEach(z=>totals[z.currency]=(totals[z.currency]||0)+Number(z.amount||0));return{Client:name(v.id),Téléphone:v.phone||'',Pays:market[v.country_code]?.country_name||v.country_code||'',Inscription:cleanDate(v.created_at),Courses:cr.length,Dépenses:Object.entries(totals).map(([c,n])=>money(n,c)).join(' • ')}});
  const chauffeurs=drivers.map(d=>{const q=p[d.user_id]||{},l=loc[d.user_id]||{},v=vehicles.find(z=>z.driver_id===d.user_id||z.owner_id===d.user_id)||{},pay=payouts.find(z=>z.driver_id===d.user_id)||{};return{Chauffeur:name(d.user_id),Téléphone:q.phone||'',Pays:l.country_name||market[q.country_code]?.country_name||q.country_code||'',Statut:d.status||'',Vérifié:d.is_verified?'Oui':'Non',Note:Number(d.rating||0),Courses:Number(d.total_rides||0),Véhicule:[v.make,v.model].filter(Boolean).join(' '),Immatriculation:v.plate_number||'',Paie:pay.payout_status||'Non configurée'}});
  const courses=rides.map(r=>({Date:cleanDate(r.created_at),Pays:r.pickup_country_name||market[r.pickup_country_code]?.country_name||r.pickup_country_code||'',Client:name(r.client_id),Chauffeur:name(r.driver_id),Départ:r.pickup_address||'',Destination:r.destination_address||'',Distance_km:Number(r.estimated_distance_km||0),Durée_min:Number(r.estimated_duration_min||0),'Prix standard':Number(r.standard_price??r.estimated_price??0),'Prix proposé':r.customer_proposed_price==null?'':Number(r.customer_proposed_price),'Prix convenu':Number(r.agreed_price??r.final_price??r.estimated_price??0),Devise:r.currency||'',Paiement:r.payment_method||'',Statut:r.status||''}));
  const paiements=payments.map(z=>({Date:cleanDate(z.created_at),Client:name(z.user_id),Course:z.ride_id||'',Méthode:z.provider||z.method_type||'',Montant:Number(z.amount||0),Devise:z.currency||'',Statut:z.status||'',Référence:z.provider_reference||''}));
  const paie=payouts.map(z=>({Chauffeur:name(z.driver_id),Pays:market[z.country_code]?.country_name||z.country_code||'',Mode:z.payout_method||'',Titulaire:z.account_holder||'',Banque:z.bank_name||'',Compte:z.iban_or_account||'',SWIFT:z.bank_bic_swift||'',Opérateur:z.mobile_operator||'',Téléphone:z.phone_number||'',Devise:z.payout_currency||'',Statut:z.payout_status||''}));
  const documents=docs.map(z=>({Date:cleanDate(z.created_at),Chauffeur:name(z.driver_id),Type:z.document_type||'',Fichier:z.file_name||'',Pays:market[z.country_code]?.country_name||z.country_code||'',Statut:z.status||'',Motif:z.rejection_reason||''}));
  const tarifs=pricing.map(z=>({Pays:market[z.country_code]?.country_name||z.country_code||'',Code:z.country_code||'',Service:z.service_type||'',Base:Number(z.base_fare||0),'Par km':Number(z.per_km||0),'Par minute':Number(z.per_minute||0),Minimum:Number(z.minimum_fare||0),Réservation:Number(z.booking_fee||0),Devise:z.currency||''}));
  const revenue={};payments.filter(z=>z.status==='paid').forEach(z=>revenue[z.currency]=(revenue[z.currency]||0)+Number(z.amount||0));
  const synth=[{Indicateur:'Clients',Valeur:clients.length},{Indicateur:'Chauffeurs',Valeur:chauffeurs.length},{Indicateur:'Courses totales',Valeur:courses.length},{Indicateur:'Courses terminées',Valeur:rides.filter(r=>r.status==='completed').length},{Indicateur:'Courses actives',Valeur:rides.filter(r=>['searching','accepted','driver_arriving','in_progress'].includes(r.status)).length},{Indicateur:'Documents à contrôler',Valeur:docs.filter(d=>d.status==='pending').length},...Object.entries(revenue).map(([c,v])=>({Indicateur:`Recettes ${c}`,Valeur:money(v,c)}))];
  return{synth,clients,chauffeurs,courses,paiements,paie,documents,tarifs};
}
function download(name,sheets){const wb=XLSX.utils.book_new();Object.entries(sheets).forEach(([n,r])=>addSheet(wb,n,r));wb.Props={Title:'FAST N°1 - Export de gestion',Subject:'Export Excel FAST',Author:'FAST N°1',Company:'FAST N°1',CreatedDate:new Date()};XLSX.writeFile(wb,`FAST_${name}_${new Date().toISOString().slice(0,10)}.xlsx`,{compression:true})}
async function run(type,btn){if(!window.XLSX)return toastMsg('Module Excel indisponible.');const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Préparation…'}try{const d=buildData(await snapshot());if(type==='full')download('Pilotage_Complet',{'Synthèse':d.synth,'Courses':d.courses,'Clients':d.clients,'Chauffeurs':d.chauffeurs,'Paiements':d.paiements,'Paie chauffeurs':d.paie,'Documents':d.documents,'Tarifs':d.tarifs});else if(type==='finance')download('Finance',{'Synthèse':d.synth,'Paiements':d.paiements,'Paie chauffeurs':d.paie,'Courses':d.courses});else if(type==='operations')download('Operations',{'Courses':d.courses,'Chauffeurs':d.chauffeurs,'Clients':d.clients,'Documents':d.documents});else if(type==='rides')download('Courses',{'Courses':d.courses});toastMsg('Export Excel généré.')}catch(e){toastMsg('Export impossible : '+(e.message||e))}finally{if(btn){btn.disabled=false;btn.textContent=old}}}
function style(){if($('modernExportStyle'))return;const s=document.createElement('style');s.id='modernExportStyle';s.textContent=`.export-hero{background:linear-gradient(135deg,#071b3f,#0b57d0);color:#fff;border:0}.export-hero p{color:#dbeafe}.export-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px;margin-top:16px}.export-card{padding:22px;border:1px solid #dfe7f1;border-radius:20px;background:linear-gradient(180deg,#fff,#f8fbff)}.export-card .export-icon{display:grid;place-items:center;width:46px;height:46px;border-radius:14px;background:#eaf3ff;font-size:22px}.export-card h3{margin:16px 0 7px}.export-card p{margin:0 0 18px;color:#667085;line-height:1.55;font-size:12px}.export-card button{width:100%;min-height:44px;border:0;border-radius:12px;background:#0b57d0;color:#fff;font-weight:850;cursor:pointer}.export-card.primary-export{border-color:#9fc4ff;box-shadow:0 14px 34px rgba(11,87,208,.09)}.export-note{display:flex;gap:10px;align-items:flex-start;padding:14px 16px;border-radius:14px;background:#f0f7ff;color:#33506f;font-size:12px;margin-top:16px}@media(max-width:760px){.export-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function bind(){style();document.querySelectorAll('[data-modern-export]').forEach(b=>b.onclick=()=>run(b.dataset.modernExport,b));$('exportBtn')?.addEventListener('contextmenu',e=>{e.preventDefault();run('full',$('exportBtn'))})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
