(()=>{
'use strict';
const MAIN_API='https://hmwxwzfcpdvgzjgxruup.supabase.co/functions/v1/fast-admin-api';
const MANUAL_API='https://hmwxwzfcpdvgzjgxruup.supabase.co/functions/v1/fast-admin-manual';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=()=>localStorage.getItem('fast_admin_token')||'';
let snapshotCache=null;

function toast(message){const t=$('toast');if(!t)return;t.textContent=String(message||'');t.classList.add('on');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('on'),3000)}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function refreshAdmin(){snapshotCache=null;const b=$('refreshBtn');if(b)b.click()}
async function request(base,path,opts={}){
  const headers={'Content-Type':'application/json','x-fast-admin-token':token(),...(opts.headers||{})};
  const r=await fetch(base+path,{...opts,headers,cache:'no-store'});let d={};try{d=await r.json()}catch{}
  if(r.status===401)throw new Error('Session administrateur expirée. Reconnectez-vous.');
  if(!r.ok||d.ok===false)throw new Error(d.error||d.detail||`HTTP ${r.status}`);
  return d;
}
async function snapshot(force=false){if(snapshotCache&&!force)return snapshotCache;const d=await request(MAIN_API,'/snapshot');snapshotCache=d.data||{};return snapshotCache}
function formValue(id){return ($(id)?.value||'').trim()}
function checked(id){return !!$(id)?.checked}
function setBusy(btn,on,label='Enregistrer'){if(!btn)return;btn.disabled=on;btn.textContent=on?'Enregistrement…':label}
function arrayFromCsv(value){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean)}
function countryLabel(code,markets){const m=(markets||[]).find(x=>x.country_code===code);return m?`${m.country_name} (${code})`:code||'—'}
function profileName(p){return `${p?.first_name||''} ${p?.last_name||''}`.trim()||String(p?.id||'').slice(0,8)}
function input(label,id,value='',type='text',extra=''){return `<label>${esc(label)}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function select(label,id,options,value=''){return `<label>${esc(label)}<select id="${id}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`}
function manualShell(inner){return `<div class="manual-form">${inner}</div>`}

function userCreateHtml(role){const driver=role==='driver';return manualShell(`
  <div class="manual-grid">
    ${input('Prénom','manualFirstName')}${input('Nom','manualLastName')}
    ${input('E-mail de connexion','manualEmail','','email','autocomplete="off"')}${input('Téléphone','manualPhone','','tel')}
    ${input('Code pays (ex. CG)','manualCountry','CG','','maxlength="2"')}${input('Mot de passe provisoire','manualPassword','','password','autocomplete="new-password" minlength="8"')}
  </div>
  ${driver?'<label class="manual-check"><input id="manualVerified" type="checkbox"> Valider immédiatement le chauffeur</label>':''}
  <p class="manual-help">Le compte est créé directement dans FAST. L’e-mail est confirmé par l’administration et le mot de passe pourra ensuite être changé par l’utilisateur.</p>
  <div class="manual-actions"><button type="button" class="primary" id="manualSaveUser">Créer ${driver?'le chauffeur':'le client'}</button></div>`)}
async function openCreateUser(role){openModal(role==='driver'?'Ajouter manuellement un chauffeur':'Ajouter manuellement un client',userCreateHtml(role));$('manualSaveUser').onclick=()=>saveCreateUser(role)}
async function saveCreateUser(role){const btn=$('manualSaveUser');setBusy(btn,true,`Créer ${role==='driver'?'le chauffeur':'le client'}`);try{
  const payload={role,first_name:formValue('manualFirstName'),last_name:formValue('manualLastName'),email:formValue('manualEmail'),phone:formValue('manualPhone'),country_code:formValue('manualCountry').toUpperCase(),password:$('manualPassword')?.value||'',is_verified:role==='driver'&&checked('manualVerified')};
  await request(MANUAL_API,'/user/create',{method:'POST',body:JSON.stringify(payload)});closeModal();toast(role==='driver'?'Chauffeur ajouté':'Client ajouté');refreshAdmin();
}catch(e){toast(e.message)}finally{setBusy(btn,false,`Créer ${role==='driver'?'le chauffeur':'le client'}`)}}

async function openEditUser(role){try{const s=await snapshot(true),profiles=(s.profiles||[]).filter(p=>String(p.role)===role);if(!profiles.length)return toast(role==='driver'?'Aucun chauffeur à modifier.':'Aucun client à modifier.');const drivers=s.drivers||[],markets=s.market_configs||[];const opts=profiles.map(p=>[p.id,`${profileName(p)} • ${p.phone||'sans téléphone'} • ${countryLabel(p.country_code,markets)}`]);openModal(role==='driver'?'Modifier manuellement un chauffeur':'Modifier manuellement un client',manualShell(`
  ${select(role==='driver'?'Chauffeur':'Client','manualUserSelect',opts,profiles[0].id)}
  <div id="manualUserEditFields"></div>
  <div class="manual-actions"><button type="button" class="primary" id="manualUpdateUser">Enregistrer les modifications</button></div>`));
  const fill=()=>{const p=profiles.find(x=>x.id===$('manualUserSelect').value)||profiles[0],d=drivers.find(x=>x.user_id===p.id);$('manualUserEditFields').innerHTML=`<div class="manual-grid">${input('Prénom','manualEditFirstName',p.first_name||'')}${input('Nom','manualEditLastName',p.last_name||'')}${input('E-mail','manualEditEmail','','email','placeholder="Laisser vide pour conserver"')}${input('Téléphone','manualEditPhone',p.phone||'','tel')}${input('Code pays','manualEditCountry',p.country_code||'CG','','maxlength="2"')}${role==='driver'?select('Statut','manualEditDriverStatus',[['offline','Hors ligne'],['available','Disponible'],['busy','Occupé']],d?.status||'offline'):''}</div>${role==='driver'?`<label class="manual-check"><input id="manualEditVerified" type="checkbox" ${d?.is_verified?'checked':''}> Chauffeur vérifié</label>`:''}`};};
  fill();$('manualUserSelect').onchange=fill;$('manualUpdateUser').onclick=()=>saveEditUser(role);
}catch(e){toast(e.message)}}
async function saveEditUser(role){const btn=$('manualUpdateUser');setBusy(btn,true);try{const payload={id:$('manualUserSelect').value,first_name:formValue('manualEditFirstName'),last_name:formValue('manualEditLastName'),email:formValue('manualEditEmail'),phone:formValue('manualEditPhone'),country_code:formValue('manualEditCountry').toUpperCase()};if(role==='driver'){payload.status=$('manualEditDriverStatus').value;payload.is_verified=checked('manualEditVerified')}await request(MANUAL_API,'/user/update',{method:'POST',body:JSON.stringify(payload)});closeModal();toast('Modifications enregistrées');refreshAdmin()}catch(e){toast(e.message)}finally{setBusy(btn,false)}}

async function filePayload(inputId){const f=$(inputId)?.files?.[0];if(!f)return{};if(f.size>8*1024*1024)throw new Error('Fichier trop volumineux : 8 Mo maximum.');const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('Lecture du fichier impossible.'));r.readAsDataURL(f)});const i=dataUrl.indexOf(',');return{file_b64:i>=0?dataUrl.slice(i+1):'',file_name:f.name,mime_type:f.type||'application/octet-stream'}}
function docFields({drivers,profiles,markets,doc=null,create=false}){const driverOpts=drivers.map(d=>{const p=profiles.find(x=>x.id===d.user_id);return[d.user_id,`${profileName(p)} • ${p?.phone||'sans téléphone'}`]});const type=doc?.document_type||'identity',status=doc?.status||'pending';return `${create?select('Chauffeur','manualDocDriver',driverOpts,driverOpts[0]?.[0]||''):''}<div class="manual-grid">${input('Type de document','manualDocType',type)}${input('Code pays','manualDocCountry',doc?.country_code||'CG','','maxlength="2"')}${select('Statut','manualDocStatus',[['pending','En attente'],['approved','Validé'],['rejected','Refusé']],status)}${input('Expiration','manualDocExpiry',doc?.expires_at||'','date')}</div><label>Motif du refus<textarea id="manualDocReason" rows="3" placeholder="Obligatoire uniquement si refusé">${esc(doc?.rejection_reason||'')}</textarea></label><label>${create?'Fichier':'Remplacer le fichier (facultatif)'}<input id="manualDocFile" type="file" accept="image/*,.pdf,.doc,.docx"></label><p class="manual-help">Taille maximale : 8 Mo. ${create?'Le fichier sera stocké dans le dossier privé du chauffeur.':'Laissez le fichier vide pour conserver le document actuel.'}</p>`}
async function openCreateDocument(){try{const s=await snapshot(true),drivers=s.drivers||[],profiles=s.profiles||[],markets=s.market_configs||[];if(!drivers.length)return toast('Ajoutez d’abord un chauffeur.');openModal('Ajouter manuellement un document',manualShell(`${docFields({drivers,profiles,markets,create:true})}<div class="manual-actions"><button type="button" class="primary" id="manualSaveDoc">Ajouter le document</button></div>`));$('manualSaveDoc').onclick=saveCreateDocument}catch(e){toast(e.message)}}
async function saveCreateDocument(){const btn=$('manualSaveDoc');setBusy(btn,true,'Ajouter le document');try{const file=await filePayload('manualDocFile');const payload={driver_id:$('manualDocDriver').value,document_type:formValue('manualDocType'),country_code:formValue('manualDocCountry').toUpperCase(),status:$('manualDocStatus').value,expires_at:formValue('manualDocExpiry'),rejection_reason:formValue('manualDocReason'),...file};await request(MANUAL_API,'/document/create',{method:'POST',body:JSON.stringify(payload)});closeModal();toast('Document ajouté');refreshAdmin()}catch(e){toast(e.message)}finally{setBusy(btn,false,'Ajouter le document')}}
async function openEditDocument(){try{const s=await snapshot(true),docs=s.driver_documents||[],drivers=s.drivers||[],profiles=s.profiles||[],markets=s.market_configs||[];if(!docs.length)return toast('Aucun document à modifier.');const opts=[...docs].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(d=>{const p=profiles.find(x=>x.id===d.driver_id);return[d.id,`${profileName(p)} • ${d.document_type} • ${d.status}`]});openModal('Modifier manuellement un document',manualShell(`${select('Document','manualDocSelect',opts,opts[0][0])}<div id="manualDocEditFields"></div><div class="manual-actions"><button type="button" class="primary" id="manualUpdateDoc">Enregistrer le document</button></div>`));const fill=()=>{const d=docs.find(x=>x.id===$('manualDocSelect').value)||docs[0];$('manualDocEditFields').innerHTML=docFields({drivers,profiles,markets,doc:d,create:false})};fill();$('manualDocSelect').onchange=fill;$('manualUpdateDoc').onclick=saveEditDocument}catch(e){toast(e.message)}}
async function saveEditDocument(){const btn=$('manualUpdateDoc');setBusy(btn,true);try{const file=await filePayload('manualDocFile');const payload={id:$('manualDocSelect').value,document_type:formValue('manualDocType'),country_code:formValue('manualDocCountry').toUpperCase(),status:$('manualDocStatus').value,expires_at:formValue('manualDocExpiry'),rejection_reason:formValue('manualDocReason'),...file};await request(MANUAL_API,'/document/update',{method:'POST',body:JSON.stringify(payload)});closeModal();toast('Document modifié');refreshAdmin()}catch(e){toast(e.message)}finally{setBusy(btn,false)}}

async function openManualSettings(){try{const s=await snapshot(true),markets=s.market_configs||[],pricing=s.market_pricing||[];if(!markets.length)return toast('Aucun pays configuré.');const options=markets.map(m=>[m.country_code,`${m.country_name} (${m.country_code})`]);openModal('Paramétrage manuel FAST',manualShell(`${select('Pays','manualMarketSelect',options,options[0][0])}<div id="manualMarketFields"></div><div class="manual-actions"><button type="button" class="primary" id="manualSaveMarket">Enregistrer les paramètres</button></div>`));const fill=()=>{const m=markets.find(x=>x.country_code===$('manualMarketSelect').value)||markets[0],p=pricing.find(x=>x.country_code===m.country_code&&x.service_type==='standard')||pricing.find(x=>x.country_code===m.country_code);$('manualMarketFields').innerHTML=`<div class="manual-grid">${input('Nom du pays','manualMarketName',m.country_name||'')}${input('Devise','manualMarketCurrency',m.currency||'XAF','','maxlength="3"')}${input('Locale','manualMarketLocale',m.locale||'fr-FR')}<label class="manual-check manual-check-box"><input id="manualMarketEnabled" type="checkbox" ${m.enabled?'checked':''}> Pays activé</label></div><div class="manual-grid">${input('Méthodes de paiement (séparées par virgule)','manualPaymentMethods',(m.payment_methods||[]).join(', '))}${input('Méthodes de paie chauffeur','manualPayoutMethods',(m.payout_methods||[]).join(', '))}${input('Opérateurs Mobile Money','manualMobileOperators',(m.mobile_money_operators||[]).join(', '))}${input('Documents requis','manualDocRequirements',(m.document_requirements||[]).join(', '))}</div>${p?`<hr class="manual-sep"><h3>Tarif standard</h3><input id="manualPricingId" type="hidden" value="${esc(p.id)}"><div class="manual-grid manual-grid-3">${input('Prise en charge','manualBaseFare',p.base_fare??0,'number','min="0" step="0.01"')}${input('Prix / km','manualPerKm',p.per_km??0,'number','min="0" step="0.01"')}${input('Prix / min','manualPerMin',p.per_minute??0,'number','min="0" step="0.01"')}${input('Minimum','manualMinimumFare',p.minimum_fare??0,'number','min="0" step="0.01"')}${input('Frais réservation','manualBookingFee',p.booking_fee??0,'number','min="0" step="0.01"')}</div>`:'<p class="manual-help">Aucun tarif standard existant pour ce pays.</p>'}`};fill();$('manualMarketSelect').onchange=fill;$('manualSaveMarket').onclick=saveManualSettings}catch(e){toast(e.message)}}
async function saveManualSettings(){const btn=$('manualSaveMarket');setBusy(btn,true);try{const code=$('manualMarketSelect').value,currency=formValue('manualMarketCurrency').toUpperCase();const market={country_code:code,country_name:formValue('manualMarketName'),currency,locale:formValue('manualMarketLocale')||'fr-FR',enabled:checked('manualMarketEnabled'),payment_methods:arrayFromCsv(formValue('manualPaymentMethods')),payout_methods:arrayFromCsv(formValue('manualPayoutMethods')),mobile_money_operators:arrayFromCsv(formValue('manualMobileOperators')),document_requirements:arrayFromCsv(formValue('manualDocRequirements'))};await request(MAIN_API,'/market/save',{method:'POST',body:JSON.stringify(market)});const pricingId=$('manualPricingId')?.value;if(pricingId){await request(MAIN_API,'/pricing/update',{method:'POST',body:JSON.stringify({id:pricingId,base_fare:Number(formValue('manualBaseFare')),per_km:Number(formValue('manualPerKm')),per_minute:Number(formValue('manualPerMin')),minimum_fare:Number(formValue('manualMinimumFare')),booking_fee:Number(formValue('manualBookingFee')),currency})})}closeModal();toast('Paramètres enregistrés');refreshAdmin()}catch(e){toast(e.message)}finally{setBusy(btn,false)}}

function injectStyles(){if($('fastManualAdminStyles'))return;const style=document.createElement('style');style.id='fastManualAdminStyles';style.textContent=`
.manual-action-group{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-left:auto}.manual-action-btn{border:1px solid #c9d7e8;background:#fff;color:#17345f;border-radius:10px;padding:9px 12px;font-weight:800;cursor:pointer;white-space:nowrap}.manual-action-btn.primary-manual{background:#0b57d0;color:#fff;border-color:#0b57d0}.manual-form{display:grid;gap:16px}.manual-form label{display:grid;gap:7px;font-size:13px;font-weight:750;color:#344054}.manual-form input,.manual-form select,.manual-form textarea{width:100%;border:1px solid #d0d9e6;border-radius:10px;padding:11px 12px;background:#fff;color:#172033;outline:none}.manual-form textarea{resize:vertical}.manual-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.manual-grid-3{grid-template-columns:repeat(3,minmax(0,1fr))}.manual-check{display:flex!important;grid-template-columns:auto 1fr!important;align-items:center;gap:9px!important}.manual-check input{width:auto!important}.manual-check-box{padding-top:26px}.manual-help{margin:0;color:#667085;font-size:12px;line-height:1.5}.manual-actions{display:flex;justify-content:flex-end;gap:8px;padding-top:4px}.manual-actions .primary{min-width:190px}.manual-sep{width:100%;border:0;border-top:1px solid #e5eaf1;margin:2px 0}.manual-form h3{margin:0}.toolbar .manual-action-group{margin-left:auto}@media(max-width:720px){.manual-grid,.manual-grid-3{grid-template-columns:1fr}.manual-check-box{padding-top:0}.manual-action-group{width:100%;margin-left:0}.manual-action-btn{flex:1}.manual-actions .primary{width:100%}}
`;document.head.appendChild(style)}
function button(text,handler,primary=false){const b=document.createElement('button');b.type='button';b.className='manual-action-btn'+(primary?' primary-manual':'');b.textContent=text;b.addEventListener('click',handler);return b}
function addToolbarActions(pageId,items){const toolbar=document.querySelector(`#${pageId} .toolbar`);if(!toolbar||toolbar.querySelector('.manual-action-group'))return;const group=document.createElement('div');group.className='manual-action-group';items.forEach(([text,handler,primary])=>group.appendChild(button(text,handler,primary)));toolbar.appendChild(group)}
function bind(){injectStyles();addToolbarActions('page-drivers',[['Ajouter un chauffeur',()=>openCreateUser('driver'),true],['Modifier un chauffeur',()=>openEditUser('driver'),false]]);addToolbarActions('page-clients',[['Ajouter un client',()=>openCreateUser('client'),true],['Modifier un client',()=>openEditUser('client'),false]]);addToolbarActions('page-documents',[['Ajouter un document',openCreateDocument,true],['Modifier un document',openEditDocument,false]]);const head=document.querySelector('#page-markets .panel .panel-head');if(head&&!head.querySelector('[data-manual-settings]')){const b=button('Paramétrage manuel',openManualSettings,false);b.dataset.manualSettings='1';head.appendChild(b)}
  document.addEventListener('click',e=>{const nav=e.target.closest('#nav button[data-page]');if(nav)setTimeout(bind,60)});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
